version: '3'
services:
  teb-tutorial-ws:
    build: .
    image: j3soon/ros2-teb-tutorial-ws
    container_name: ros2-teb-tutorial-ws
    stdin_open: true
    tty: true
    privileged: true
    command: /bin/bash
    network_mode: host
    working_dir: /home/ros2-agv-essentials/teb_tutorial_ws
    environment:
      - DISPLAY=${DISPLAY}
      - CATKIN_WS=/home/ros2-agv-essentials/teb_tutorial_ws
      # If you want to access GPU, please uncomment the lines below.
      # Reference : https://docs.docker.com/compose/gpu-support/
      # deploy:
      #   resources:
      #     reservations:
      #       devices:
      #         - driver: nvidia
      #           count: all
      #           capabilities: [ gpu ]
    volumes:
      # Mount local timezone into container. ( Readonly )
      # Reference: https://stackoverflow.com/questions/57607381/how-do-i-change-timezone-in-a-docker-container
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # Mount X11 server
      - /tmp/.X11-unix:/tmp/.X11-unix
      # Direct Rendering Infrastructure
      - /dev/dri:/dev/dri
      # Mount sound card to prevent Gazebo warning.
      - /dev/snd:/dev/snd
      # Mount Gazebo models directory to reuse models downloaded during first launch.
      # Reference: https://answers.ros.org/question/365658
      - ./cache/.gazebo:/home/user/.gazebo
      # Mount workspace
      - ../..:/home/ros2-agv-essentials
